version: "3.8"

services:
  analytics-frontend:
    image: registry.melior.ai/analytics-dashboard:latest
    network_mode: host
    volumes:
      - ./config:/src/config
    env_file:
      - .env
    ports:
      - "3000:3000"
